// lib/services/voice_parser_service.dart

class VoiceParserService {
  /// Aturan pemetaan kata kunci ke Kategori
  static const Map<String, List<String>> _rules = {
    'Makanan & Minuman': [
      'nasi',
      'warteg',
      'makan',
      'mie',
      'gacoan',
      'udang',
      'minum',
      'kopi',
      'bakso',
      'ayam',
      'soto',
      'sate',
      'bubur',
      'roti',
      'jajan',
      'gorengan',
      'esteh',
      'camilan',
      'warung',
      'restoran',
      'cafe',
      'cemilan',
      'snack',
      'seblak',
      'martabak',
      'masakan',
      'kedai',
      'teh',
      'jus',
      'buah',
      'sayur',
      'daging',
      'ikan',
      'telur',
      'tahu',
      'tempe',
      'sambal',
      'kerupuk',
      'sarapan',
      'makan siang',
      'makan malam',
      'delivery',
      'grabfood',
      'gofood',
      'chitato',
      'cireng',
      'cilok',
      'dimsum',
      'boba',
      'matcha',
      'latte',
      'espresso',
      'ayam goreng',
      'pecel',
      'lele',
      'padang',
      'minuman',
      'makanan',
      'lapar',
      'haus',
      'perut',
      'ngopi',
      'bakmie',
      'burger',
      'pizza',
      'fried chicken',
      'kfc',
      'mcd',
      'hokben',
      'bento',
      'bakwan',
      'tahu gejrot',
      'geprek',
      'mentai',
      'sushi',
      'ramen',
      'spaghetti',
      'waffle',
      'pancake',
      'croissant',
      'donat',
      'coklat',
      'eskrim',
      'popice',
      'thai tea',
      'air mineral',
      'aqua',
      'le minerale',
      'pukis',
      'pancong',
      'bubur ayam',
      'mie ayam',
      'siomay',
      'batagor',
      'pempek',
      'tekwan',
      'kerak telor',
      'gado-gado',
      'karedok',
      'rawon',
      'lontong',
      'opor',
      'rendang',
      'dendeng',
      'tongkol',
      'aneka kue',
      'pastry',
      'bakpao',
      'dim sum',
      'salad',
      'bistik',
      'kebab',
      'tacos',
      'steak',
      'seafood',
      'kepiting',
      'kerang',
      'cumi',
      'udang bakar',
      'ikan bakar',
      'pepes',
      'sayur asem',
      'sayur lodeh',
      'capcay',
      'fuyunghai',
      'kwetiau',
      'bihun',
      'bakso malang',
      'mie kocok',
      'mie aceh',
      'seblak basah',
      'baso aci',
      'cimol',
      'tahu walik',
      'cireng isi',
      'krupuk',
      'emping',
      'rempeyek',
      'es krim',
      'gelato',
      'kopi susu',
      'americano',
      'cappuccino',
      'frappe',
      'milkshake',
      'smoothie',
      'yakult',
      'susu',
      'yogurt',
      'kefir',
      'jamu kunyit',
      'beras kencur',
      'sinom',
      'starbucks',
      'kopikenangan',
      'janji jiwa',
      'chatime',
      'mixue',
      'kopsu',
      'subway',
      'solaria',
      'dcost',
      'richeese',
      'jco',
      'breadtalk',
      'mako',
      'rotio',
      'ampera',
      'sederhana',
      'bumbu desa',
      'tahu sumedang',
      'pisang goreng',
      'molen',
      'pastel',
      'risoles',
      'lemper',
      'lumpia',
      'bakpia',
      'wingko',
      'getuk',
      'klepon',
      'cenil',
      'onde-onde',
      'nagasari',
      'apem',
      'serabi',
      'puding',
      'agar-agar',
      'jeli',
      'sirup',
      'marjan',
      'abc',
      'tehbotol',
      'sosro',
      'tehpucuk',
      'ultra milk',
      'indomilk',
      'milo',
      'ovaltine',
      'nutrisari',
      'good day',
      'luwak white koffie',
      'nescafe',
      'torabika',
      'kapal api',
      'indomie',
      'sedap',
      'sarimi',
      'pop mie',
      'samyang',
      'shin ramyun',
      'keju',
      'mentega',
      'margarin',
      'meses',
      'selai',
      'madu',
      'sereal',
      'oatmeal',
      'kuaci',
      'kacang atom',
      'sukro',
      'tictac',
      'lays',
      'pringles',
      'taro',
      'qtela',
      'kusuka',
      'oreo',
      'silverqueen',
      'cadbury',
      'bengbeng',
      'chocolatos',
      'wafer',
      'biskuit',
      'khong guan',
      'roma',
      'tanggo',
      'mentos',
      'relaxa',
      'kopiko',
      'sugus',
      'permen',
      'permen karet',
      'nuget',
      'sosis',
      'bakso sapi',
      'bakso ayam',
      'kornet',
      'sardes',
      'sarden',
      'abon',
      'bumbu racik',
      'saos',
      'kecap',
      'mayonais',
      'saus tiram',
      'minyak goreng',
      'filma',
      'bimoli',
      'sunco',
      'tropicanaslim',
      'gula',
      'garam',
      'merica',
      'ketumbar',
      'pala',
      'cengkeh',
      'kayu manis',
      'serai',
      'lengkuas',
      'jahe',
      'kunyit',
      'kencur',
      'bawang merah',
      'bawang putih',
      'bawang bombay',
      'cabai',
      'cabe rawit',
      'tomat',
      'kentang',
      'wortel',
      'buncis',
      'kol',
      'sawi',
      'kangkung',
      'bayam',
      'daun singkong',
      'daun pepaya',
      'labu siam',
      'terong',
      'petai',
      'jengkol',
      'toge',
      'jamur',
      'jagung',
      'singkong',
      'ubi',
      'talas',
      'pisang',
      'apel',
      'jeruk',
      'mangga',
      'anggur',
      'stroberi',
      'semangka',
      'melon',
      'pepaya',
      'nanas',
      'durian',
      'rambutan',
      'kelengkeng',
      'manggis',
      'salak',
      'alpukat',
      'nangka',
      'kelapa',
      'santan',
      'kara',
      'baking powder',
      'ragi',
      'tepung terigu',
      'segitiga biru',
      'tepung beras',
      'tepung ketan',
      'tepung tapioka',
      'sagu',
      'maizena',
      'bihun jagung',
      'suun',
      'makaroni',
      'pasta',
      'lasagna',
      'risotto',
      'paella',
      'tom yum',
      'laksa',
      'pho',
      'udon',
      'soba',
      'takoyaki',
      'okonomiyaki',
      'onigiri',
      'kimbap',
      'tteokbokki',
      'odeng',
      'corndog',
      'hotdog',
      'sandwich',
      'croffle',
      'churros',
      'macaron',
      'cupcake',
      'brownies',
      'cheese cake',
      'tiramisu',
      'black forest',
      'lapis legit',
      'lapis surabaya',
      'kue sus',
      'eclair',
      'tart',
      'pie susu',
      'bika ambon',
      'bolu',
      'chiffon',
      'sponge cake',
      'muffin',
      'scone',
      'cookies',
      'nastor',
      'nastar',
      'kastengel',
      'putri salju',
      'kue bawang',
      'kue satu',
      'kue dahlia',
      'semprit',
      'kue ku',
      'kue mangkok',
      'kue talam',
      'kue bugis',
      'putu ayu',
      'putu bambu',
      'klepon',
      'onde-onde',
      'lupis',
      'tiwul',
      'gatot',
      'sawut',
      'jongkong',
      'bubur sumsum',
      'bubur candil',
      'bubur kacang hijau',
      'bubur ketan hitam',
      'kolak',
      'pisang ijo',
      'es pisang ijo',
      'es teler',
      'es campur',
      'es buah',
      'es degan',
      'es kelapa muda',
      'es tebu',
      'es tebu murni',
      'es jeruk',
      'es sirup',
      'es podeng',
      'es doger',
      'es puter',
      'es lilin',
      'es mambo',
      'es tungtung',
      'ice cream',
      'sundae',
      'parfait',
      'sorbet',
      'frozen yogurt',
      'smoothie bowl',
      'chia pudding',
      'overnight oats',
      'kombucha',
      'infused water',
      'lemonade',
      'mojito',
      'mocktail',
      'cocktail',
      'beer',
      'bintang',
      'anker',
      'proost',
      'guinness',
      'heineken',
      'soju',
      'sake',
      'wine',
      'whiskey',
      'vodka',
      'rum',
      'gin',
      'tequila',
      'tuak',
      'ciyu',
      'arak',
      'badak',
      'teh talua',
      'wedang ronde',
      'wedang jahe',
      'sekoteng',
      'bajigur',
      'bandrek',
      'stmj',
      'telur setengah matang',
      'jamu',
      'tolak angin',
      'antangin',
      'bejo',
      'habbatussauda',
      'minyak zaitun',
      'cuka apel',
      'chia seed',
      'flaxseed',
      'almond',
      'kacang mede',
      'pistachio',
      'walnut',
      'hazelnut',
      'kacang tanah',
      'kacang hijau',
      'kacang merah',
      'kedelai',
      'edamame',
      'tauco',
      'tahu sutra',
      'tahu pong',
      'tahu bulat',
      'tempe mendoan',
      'tempe gembus',
      'oncom',
      'oncom bandung',
      'leunca',
      'takokak',
      'daun kemangi',
      'lalapan',
      'pete',
      'jengki',
      'terasi',
      'petis',
      'tauco',
      'kecap asin',
      'kecap inggris',
      'minyak wijen',
      'saos sambal',
      'saos tomat',
      'saos tiram',
      'bumbu bali',
      'bumbu rendang',
      'bumbu sate',
      'bumbu soto',
      'bumbu gule',
      'bumbu kare',
      'bumbu opor',
      'bumbu lodeh',
      'bumbu sayur asem',
      'bumbu ayam goreng',
      'bumbu ikan goreng',
      'bumbu nasi goreng',
      'bumbu mi goreng',
      'bumbu semur',
      'bumbu balado',
      'bumbu rica-rica',
      'bumbu woku',
      'bumbu betutu',
      'bumbu rujak',
      'bumbu gadogado',
      'bumbu pecel',
      'bumbu sate madura',
      'bumbu sate padang',
      'bumbu sate lilit',
      'cabe giling',
      'bawang giling',
      'jahe giling',
      'kunyit giling',
      'lengkuas giling',
      'pala bubuk',
      'merica bubuk',
      'lada hitam',
      'lada putih',
      'ketumbar bubuk',
      'kayu manis bubuk',
      'cengkeh bubuk',
      'jinten bubuk',
      'kapulaga bubuk',
      'asam jawa',
      'asam kandis',
      'asam gelugur',
      'daun salam',
      'daun jeruk',
      'daun pandan',
      'daun kunyit',
      'daun bawang',
      'seledri',
      'peterseli',
      'basil',
      'oregano',
      'thyme',
      'rosemary',
      'mint',
      'serai bubuk',
      'purut',
      'jeruk nipis',
      'jeruk lemon',
      'jeruk purut',
      'cuka dapur',
      'baking soda',
      'ovalet',
      'tbm',
      'sp',
      'gelatin bubuk',
      'agar bubuk',
      'nutrijell',
      'swallow',
      'mariza',
      'morin',
      'nutella',
      'skippy',
      'ceres',
      'ovomaltine',
      'lotus biscoff',
      'goldenfil',
      'chocochips',
      'kismis',
      'sukade',
      'almond slice',
      'keju kraft',
      'prochiz',
      'cheddar',
      'mozzarella',
      'parmesan',
      'cream cheese',
      'mayumi',
      'kraft',
      'heinz',
      'delmonte',
      'indofood',
      'bango',
      'sedap',
      'abc',
      'tropicanaslim',
      'diabetasol',
      'equal',
      'sucralose',
      'stevia',
      'madu rasana',
      'madu uray',
      'madu tj',
      'madu nusantara',
      'royal jelly',
      'propolis',
      'bee pollen',
    ],
    'Transportasi': [
      'bensin',
      'pertamax',
      'pertalite',
      'gojek',
      'grab',
      'ojek',
      'parkir',
      'tol',
      'kereta',
      'krl',
      'bus',
      'tiket',
      'pesawat',
      'travel',
      'taxi',
      'angkot',
      'ongkir',
      'bengkel',
      'tambal',
      'ban',
      'servis',
      'isi bensin',
      'ride',
      'grabcar',
      'gocar',
      'shuttle',
      'transport',
      'terminal',
      'stasiun',
      'penerbangan',
      'kapal',
      'pelabuhan',
      'darat',
      'laut',
      'udara',
      'uber',
      'maxim',
      'inriver',
      'bayar parkir',
      'ganti oli',
      'knalpot',
      'sparepart',
      'tour',
      'perjalanan',
      'mudik',
      'pulang kampung',
      'tiket pesawat',
      'kai',
      'commuter',
      'transjakarta',
      'taksi online',
      'rental',
      'sewa mobil',
      'sewa motor',
      'ojol',
      'karcis',
      'tiket kereta',
      'damri',
      'penerbangan',
      'boarding',
      'pass',
      'taksi',
      'angkutan',
      'tarif',
      'emoney',
      'flazz',
      'brizzi',
      'tng',
      'e-toll',
      'isi saldo tnol',
      'tambal ban',
      'cuci motor',
      'cuci mobil',
      'salon mobil',
      'servis rutin',
      'tune up',
      'ganti ban',
      'kampas rem',
      'aki',
      'kabel gas',
      'kopling',
      'rantai',
      'gir',
      'velg',
      'ban dalam',
      'tambal tubeless',
      'oli mesin',
      'oli gardan',
      'filter udara',
      'busi',
      'karburator',
      'injeksi',
      'stnk',
      'sim',
      'kir',
      'bapenda',
      'dishub',
      'pelabuhan penyeberangan',
      'kapal feri',
      'ekspedisi',
      'cargo',
      'logistik',
      'truck',
      'container',
      'trailer',
      'pickup',
      'angsuran motor',
      'kredit motor',
      'denda tilang',
      'elektronik tilang',
      'etle',
      'shell',
      'bp',
      'vivo',
      'v-power',
      'super',
      'diesel',
      'solar',
      'dex',
      'dexlite',
      'shell dex',
      'bbm',
      'bahan bakar',
      'pom bensin',
      'spbu',
      'spbuk',
      'pertashop',
      'pengisian',
      'tangki',
      'full tank',
      'karburator',
      'injektor',
      'ecu',
      'cdi',
      'koil',
      'piston',
      'ring piston',
      'klep',
      'noken as',
      'rantai keteng',
      'paking',
      'gasket',
      'radiator',
      'air radiator',
      'coolant',
      'selang radiator',
      'pompa air radiator',
      'kipas radiator',
      'thermostat',
      'v-belt',
      'roller',
      'pulley',
      'cvt',
      'oli cvt',
      'bak cvt',
      'shockbreaker',
      'shock depan',
      'shock belakang',
      'per',
      'spring',
      'as roda',
      'bearing',
      'laher',
      'tromol',
      'piringan cakram',
      'kaliper rem',
      'master rem',
      'selang rem',
      'minyak rem',
      'pedal rem',
      'tuas rem',
      'stang',
      'kemudi',
      'setir',
      'power steering',
      'oli power steering',
      'rak setir',
      'tie rod',
      'ball joint',
      'bushing',
      'stabilizer',
      'chassis',
      'rangka',
      'body',
      'fairing',
      'visor',
      'spatbor',
      'fender',
      'kap mesin',
      'pintu mobil',
      'kaca mobil',
      'wiper',
      'air wiper',
      'motor wiper',
      'kaca spion',
      'spion',
      'lampu depan',
      'headlamp',
      'lampu belakang',
      'taillight',
      'lampu sein',
      'sein',
      'lampu kabut',
      'foglamp',
      'lampu hazard',
      'hazard',
      'klakson',
      'horn',
      'relay',
      'sekring',
      'fuse',
      'kabel bodi',
      'wiring',
      'alternator',
      'dinamo starter',
      'starter',
      'kick starter',
      'pedal gas',
      'pedal kopling',
      'tuas transmisi',
      'persneling',
      'gardan',
      'oli gardan',
      'kopel',
      'propeller shaft',
      'knalpot racing',
      'header',
      'muffler',
      'resonator',
      'catalytic converter',
      'sensor o2',
      'filter oli',
      'filter bensin',
      'filter kabin',
      'ac mobil',
      'kompresor ac',
      'kondensor ac',
      'evaporator ac',
      'ekspansi ac',
      'freon ac',
      'dashboard',
      'jok mobil',
      'jok motor',
      'kulit jok',
      'busa jok',
      'karpet mobil',
      'plafon mobil',
      'kaca film',
      'audio mobil',
      'head unit',
      'speaker mobil',
      'subwoofer',
      'amplifier',
      'power amp',
      'kamera mundur',
      'sensor parkir',
      'alarm mobil',
      'central lock',
      'power window',
      'regulator window',
      'pembuka bagasi',
      'bagasi',
      'spoiler',
      'body kit',
      'talang air',
      'roof rack',
      'roof box',
      'towing bar',
      'velg racing',
      'velg kaleng',
      'ban radial',
      'ban tubeless',
      'ban bias',
      'ban pacul',
      'ban at',
      'ban mt',
      'tekanan ban',
      'isi angin',
      'nitrogen',
      'spooring',
      'balancing',
      'alignment',
      'wheel alignment',
      'camber',
      'caster',
      'toe',
      'onderdil',
      'copotan',
      'kw',
      'original',
      'oem',
      'ahm',
      'yamaha genuine part',
      'sgp',
      'kgo',
      'tmo',
      'e-money',
      'tapcash',
      'jaklingko',
      'linkaja',
      'shopeepay',
      'dana',
      'ovo',
      'gopay',
      'astrapay',
      'bluebird',
      'silverbird',
      'express',
      'taksi bandara',
      'golden bird',
      'grabcar xl',
      'gocar luxe',
      'maxim car',
      'inrive car',
      'antar jemput',
      'jemputan sekolah',
      'jemputan karyawan',
      'bis malam',
      'rosalia indah',
      'sinar jaya',
      'harapan jaya',
      'lorena',
      'kramat djati',
      'pahala kencana',
      'safari dharma raya',
      'gunung harta',
      'agramas',
      'primajasa',
      'mayasari bakti',
      'ppd',
      'kopaja',
      'metromini',
      'kwk',
      'mikrolet',
      'bemo',
      'bajaj',
      'bentor',
      'becak',
      'andong',
      'dokar',
      'delman',
      'penyeberangan',
      'kapal cepat',
      'jetfoil',
      'pelni',
      'asdp',
      'merak',
      'bakauheni',
      'ketapang',
      'gilimanuk',
      'padangbai',
      'lembar',
      'tanjung priok',
      'tanjung perak',
      'belawan',
      'soekarno hatta',
      'halim',
      'juanda',
      'ngurah rai',
      'kualanamu',
      'yia',
      'kulon progo',
      'bandara',
      'airport',
      'garuda indonesia',
      'citilink',
      'lion air',
      'batik air',
      'wings air',
      'sriwijaya air',
      'nam air',
      'airasia',
      'scoot',
      'singapore airlines',
      'emirates',
      'qatar airways',
      'cathay pacific',
      'ana',
      'jal',
      'malaysia airlines',
      'thai airways',
      'qantas',
      'klm',
      'lufthansa',
      'air france',
      'turkish airlines',
      'saudia',
      'eva air',
      'china airlines',
      'korean air',
      'vietjet',
      'jetstar',
      'biman',
      'royal brunei',
      'fids',
      'check-in',
      'bagasi prabayar',
      'kelebihan bagasi',
      'lounge bandara',
      'duty free',
      'imigrasi',
      'paspor',
      'visa',
      'boarding pass',
      'delay',
      'reschedule',
      'refund tiket',
      'no-show',
      'transit',
      'layover',
      'stopover',
      'open jaw',
      'round trip',
      'one way',
      'multi city',
      'city check-in',
      'web check-in',
      'mobile check-in',
      'self check-in',
      'bag drop',
      'security check',
      'gate',
      'runway',
      'taxiway',
      'apron',
      'atc',
      'pilot',
      'pramugari',
      'pramugara',
      'steward',
      'stewardess',
      'cabin crew',
      'purser',
      'avsec',
      'ground handling',
      'marshal',
      'pushback',
      'towing',
      'de-icing',
      'catering pesawat',
      'inflight entertainment',
      'inflight wifi',
      'amenity kit',
      'blanket',
      'pillow',
      'seatbelt',
      'life vest',
      'oxygen mask',
      'emergency exit',
      'lavatory',
      'galley',
      'window seat',
      'aisle seat',
      'bulkhead seat',
      'exit row seat',
      'legroom',
      'recline',
      'flatbed',
      'suite',
      'first class',
      'business class',
      'premium economy',
      'economy class',
      'low cost carrier',
      'lcc',
      'full service carrier',
      'fsc',
      'charter flight',
      'private jet',
      'cargo flight',
      'air cargo',
      'waybill',
      'awb',
      'customs',
      'bea cukai',
      'pabean',
      'jalur hijau',
      'jalur merah',
      'declaring',
      'duty',
      'tax',
      'vat',
      'vat refund',
      'tourist refund',
      'tax free',
      'duty paid',
      'duty not paid',
    ],
    'Kesehatan': [
      'apotek',
      'obat',
      'dokter',
      'klinik',
      'vitamin',
      'masker',
      'rs',
      'sehat',
      'medis',
      'periksa',
      'rumah sakit',
      'bidan',
      'puyer',
      'suplemen',
      'lab',
      'checkup',
      'flu',
      'sakit',
      'kesehatan',
      'imun',
      'tebus obat',
      'konsultasi',
      'radiologi',
      'bpjs',
      'asuransi',
      'suntik',
      'operasi',
      'bidan',
      'psikolog',
      'nutrisi',
      'diet',
      'protein',
      'masker medis',
      'hand sanitizer',
      'alkohol',
      'perban',
      'kasa',
      'termometer',
      'tensi',
      'bedah',
      'rawat inap',
      'rawat jalan',
      'poli',
      'igd',
      'ambulance',
      'darah',
      'lab darah',
      'rontgen',
      'usg',
      'mri',
      'fisioterapi',
      'gigi',
      'tindik',
      'akupuntur',
      'kacamata',
      'lensa',
      'softlens',
      'kruk',
      'kursi roda',
      'timbangan',
      'suplemen gym',
      'whey protein',
      'kreatin',
      'minyak ikan',
      'madu',
      'herbal',
      'jamu',
      'pijat',
      'urut',
      'refleksi',
      'spa kesehatan',
      'therapist',
      'kapsul',
      'sirup obat',
      'tetes mata',
      'tetes telinga',
      'salep',
      'plester',
      'antiseptik',
      'masker kain',
      'testpack',
      'pembalut',
      'cotton bud',
      'tissue basah antiseptik',
      'obat merah',
      'betadine',
      'paracetamol',
      'ibuprofen',
      'amoxicillin',
      'antasida',
      'oralit',
      'kesehatan mental',
      'konsultasi online',
      'telemedicine',
      'halodoc',
      'alodokter',
      'kimia farma',
      'k24',
      'century',
      'guardian',
      'watsons',
      'apotek hidup',
      'resep dokter',
      'surat sakit',
      'mc',
      'medical certificate',
      'asuransi kesehatan',
      'prudential',
      'manulife',
      'allianz',
      'axa',
      'sinarmas',
      'bni life',
      'briva bpjs',
      'iuran bpjs',
      'faskes',
      'puskesmas',
      'poliklinik',
      'spesialis',
      'internis',
      'pediatri',
      'anak',
      'obgyn',
      'kandungan',
      'bedah',
      'mata',
      'tht',
      'kulit',
      'kelamin',
      'dermatologi',
      'saraf',
      'neurologi',
      'jantung',
      'kardiologi',
      'paru',
      'pulmonologi',
      'jiwa',
      'psikiater',
      'gigi anak',
      'ortodonti',
      'behel',
      'kawat gigi',
      'cabut gigi',
      'tambal gigi',
      'scaling',
      'pembersihan karang gigi',
      'bleaching',
      'pemutihan gigi',
      'veneer',
      'crown gigi',
      'bridge gigi',
      'gigi palsu',
      'implan gigi',
      'bedah mulut',
      'akar gigi',
      'perawatan saluran akar',
      'gusi',
      'periodonsi',
      'rontgen gigi',
      'panoramik',
      'sefalometri',
      'ct scan',
      'pet scan',
      'endoskopi',
      'kolonoskopi',
      'laparoskopi',
      'biopsi',
      'patologi',
      'anatomi',
      'klinik lab',
      'prodia',
      'prodia lab',
      'parahita',
      'biomedika',
      'labkesda',
      'tes darah',
      'tes urin',
      'tes kolesterol',
      'tes gula darah',
      'hba1c',
      'tes fungsi hati',
      'sgot',
      'sgpt',
      'tes fungsi ginjal',
      'ureum',
      'kreatinin',
      'asam urat',
      'profil lipid',
      'trigliserida',
      'hdl',
      'ldl',
      'tes hbsag',
      'tes hiv',
      'tes sifilis',
      'tes narkoba',
      'tes urin kehamilan',
      'pap smear',
      'iva test',
      'mammografi',
      'usg payudara',
      'usg 4d',
      'usg fetomaternal',
      'ekokardiografi',
      'treadmill test',
      'ekg',
      'elektrokardiogram',
      'eeg',
      'elektroensefalogram',
      'emg',
      'elektromiogram',
      'audiometri',
      'spirometri',
      'tes alergi',
      'patch test',
      'skin prick test',
      'vaksin',
      'imunisasi',
      'bcg',
      'dpt',
      'polio',
      'campak',
      'mr',
      'mmr',
      'hepatitis b',
      'hib',
      'pneunokokus',
      'pcv',
      'rotavirus',
      'influenza',
      'hpv',
      'serviks',
      'dengue',
      'dbd',
      'cacar air',
      'varisela',
      'tifooid',
      'tifus',
      'hepatitis a',
      'meningitis',
      'yellow fever',
      'rabies',
      'tetanus',
      'tt',
      'booster',
      'suntik vitamin c',
      'infus whitening',
      'infus kromosom',
      'acne injection',
      'suntik jerawat',
      'keloid injection',
      'suntik keloid',
      'botoks',
      'filler',
      'benang wajah',
      'thread lift',
      'lasik',
      'operasi katarak',
      'fakoemulsifikasi',
      'vitrektomi',
      'pterigium',
      'operasi amandel',
      'tonsilektomi',
      'adenoidektomi',
      'operasi sesar',
      'sc',
      'eracs',
      'melahirkan normal',
      'persalinan',
      'gentle birth',
      'water birth',
      'home birth',
      'doula',
      'senam hamil',
      'yoga hamil',
      'pijat laktasi',
      'konselor laktasi',
      'breasfeeding',
      'pompa asi',
      'kantong asi',
      'asip',
      'susu formula',
      'sufor',
      'mpasi',
      'bubur bayi',
      'biskuit bayi',
      'puree',
      'snack bayi',
      'pampers',
      'popok',
      'diapers',
      'popok kain',
      'clodi',
      'tisu basah bayi',
      'minyak telon',
      'minyak kayu putih',
      'baby oil',
      'baby lotion',
      'baby cream',
      'bedak bayi',
      'shampoo bayi',
      'sabun bayi',
      'sabun dua in one',
      'deterjen bayi',
      'softener bayi',
      'botol susu',
      'dot',
      'sterilizer',
      'warmer',
      'stroller',
      'kereta bayi',
      'baby walker',
      'bouncer',
      'playmat',
      'baby cot',
      'kasur bayi',
      'kelambu',
      'gendongan',
      'hipseat',
      'carrier',
      'swaddle',
      'bedong',
      'gurita bayi',
      'sarung tangan bayi',
      'kaos kaki bayi',
      'tutup kepala bayi',
      'slaber',
      'celemek bayi',
      'empeng',
      'pacifier',
      'teether',
      'mainan bayi',
      'rattle',
    ],
    'Belanja': [
      'shopee',
      'tokopedia',
      'lazada',
      'tiktokshop',
      'beli',
      'belanja',
      'toko',
      'minimarket',
      'alfamart',
      'indomaret',
      'supermarket',
      'baju',
      'sepatu',
      'paket',
      'cod',
      'kebutuhan',
      'barang',
      'mall',
      'diskon',
      'promo',
      'olshop',
      'tas',
      'dompet',
      'jam tangan',
      'aksesoris',
      'gadget',
      'elektronik',
      'voucher',
      'merchant',
      'kasir',
      'bayar toko',
      'shopping',
      'bukalapak',
      'blibli',
      'elevenia',
      'jual',
      'order',
      'checkout',
      'barang online',
      'ongkir barang',
      'kaos',
      'celana',
      'jaket',
      'topi',
      'sabuk',
      'daster',
      'hijab',
      'makeup',
      'skin care',
      'parfum',
      'kardus',
      'bubblewrap',
      'ongkir',
      'resi',
      'tracking',
      'kurir',
      'jnt',
      'jne',
      'sicepat',
      'ninja',
      'anteraja',
      'goshop',
      'titip beli',
      'grosir',
      'eceran',
      'diskonan',
      'flashsale',
      'murah',
      'stok',
      'persediaan',
      'gudang',
      'packing',
      'kado',
      'hadiah',
      'souvenir',
      'bingkisan',
      'kemeja',
      'rok',
      'gamis',
      'koko',
      'sarung',
      'peci',
      'kaos kaki',
      'underwear',
      'bra',
      'boxer',
      'piyama',
      'batik',
      'tenun',
      'kain',
      'benang',
      'jarum',
      'kancing',
      'resleting',
      'hanger',
      'rak sepatu',
      'lemari',
      'koper',
      'ransel',
      'totebag',
      'slingbag',
      'card holder',
      'payung',
      'kacamata hitam',
      'ikat rambut',
      'bros',
      'kalung',
      'gelang',
      'cincin',
      'anting',
      'jam dinding',
      'pigura',
      'hiasan',
      'stiker',
      'dekorasi',
      'transmart',
      'carrefour',
      'lotte',
      'hypermart',
      'superindo',
      'giant',
      'hero',
      'aeon',
      'gs supermarket',
      'alfa midi',
      'dandan',
      'miniso',
      'daiso',
      'kkv',
      'sociolla',
      'sephora',
      'matahari',
      'ramayana',
      'sogo',
      'seibu',
      'metro',
      'hnm',
      'zara',
      'uniqlo',
      'pull and bear',
      'bershka',
      'stradivarius',
      'cotton on',
      'giordano',
      'executive',
      'pembelian',
      'belanja bulanan',
      'belanja mingguan',
      'pasar',
      'pasar tradisional',
      'pedagang',
      'warung kelontong',
      'sales',
      'outlet',
      'boutique',
      'distro',
      'factory outlet',
      'fo',
      'bazar',
      'fair',
      'expo',
      'garage sale',
      'thrift',
      'thrifting',
      'awul-awul',
      'mon',
      'preloved',
      'secondhand',
      'bekas',
      'cuci gudang',
      'clearance sale',
      'black friday',
      'cyber monday',
      'harbolnas',
      'double date',
      'satu satu',
      'dua dua',
      'tiga tiga',
      'empat empat',
      'lima lima',
      'enam enam',
      'tujuh tujuh',
      'delapan delapan',
      'sembilan sembilan',
      'sepuluh sepuluh',
      'sebelas sebelas',
      'dua belas dua belas',
      'gajian sale',
      'payday promo',
      'cashback',
      'point',
      'reward',
      'membership card',
      'kartu anggota',
      'member',
      'vip',
      'vvip',
      't-shirt',
      'polo shirt',
      'hoodie',
      'sweater',
      'cardigan',
      'blazer',
      'vest',
      'outer',
      'tunik',
      'blouse',
      'crop top',
      'tank top',
      'singlet',
      'jersey',
      'jeans',
      'chino',
      'cargo pants',
      'jogger',
      'sweatpants',
      'legging',
      'short pants',
      'hot pants',
      'rok mini',
      'rok midi',
      'rok maxi',
      'rok plisket',
      'rok tutu',
      'dress',
      'gown',
      'kebaya',
      'beskap',
      'jas',
      'tuxedo',
      'dasi',
      'dasi kupu-kupu',
      'suspender',
      'cufflinks',
      'sapu tangan',
      'scarf',
      'pashmina',
      'bergo',
      'khimar',
      'ciput',
      'inner',
      'manset',
      'sarung tangan',
      'kaos kaki',
      'stocking',
      'tights',
      'sneakers',
      'flat shoes',
      'heels',
      'wedges',
      'boots',
      'loafers',
      'oxfords',
      'mules',
      'sandals',
      'sandal jepit',
      'sandal gunung',
      'selop',
      'pantofel',
      'sepatu bola',
      'sepatu futsal',
      'sepatu basket',
      'sepatu lari',
      'running shoes',
      'sepatu roda',
      'skate shoes',
      'boot karet',
      'safety shoes',
      'tas ransel',
      'backpack',
      'daypack',
      'carrier',
      'waistbag',
      'chestbag',
      'pouch',
      'clutch',
      'handbag',
      'shoulderbag',
      'crossbody',
      'messenger bag',
      'briefcase',
      'duffel bag',
      'travel bag',
      'beauty case',
      'organizer',
      'dompet panjang',
      'dompet lipat',
      'dompet koin',
      'dompet kartu',
      'gantungan kunci',
      'pendant',
      'charms',
      'lanyard',
      'id card holder',
      'pin',
      'badge',
      'patch',
      'iron patch',
      'velcro',
      'gesper',
      'buckle',
      'ikat pinggang',
      'gesper kulit',
      'suspenders',
      'kacamata baca',
      'frame kacamata',
      'softlens berwarna',
      'cairan softlens',
      'tempat softlens',
      'aksesoris rambut',
      'jepit rambut',
      'bando',
      'jedai',
      'scrunchie',
      'karet rambut',
      'tusuk konde',
      'hairpin',
      'wig',
      'hair extension',
      'topi baseball',
      'snapback',
      'bucket hat',
      'beanie',
      'kupluk',
      'fedora',
      'panama hat',
      'beret',
      'turban',
      'helm',
      'biker mask',
      'balaclava',
      'buff',
      'earmuffs',
      'perhiasan emas',
      'emas muda',
      'emas tua',
      'antam',
      'ubs',
      'logam mulia',
      'lm',
      'perak',
      'silver',
      'platina',
      'platinum',
      'titanium',
      'stainless steel',
      'titanium steel',
      'mutiara',
      'berlian',
      'diamond',
      'gemstone',
      'batu mulia',
      'batu akik',
      'batu giok',
      'emerald',
      'ruby',
      'sapphire',
      'topaz',
      'amethyst',
      'quartz',
      'swarovski',
      'manik-manik',
      'beads',
      'kerajinan tangan',
      'diy',
      'kit',
      'bahan kain',
      'katun',
      'linen',
      'sutra',
      'silk',
      'sifon',
      'chiffon',
      'brokat',
      'lace',
      'beludru',
      'velvet',
      'denim',
      'canvas',
      'leather',
      'kulit asli',
      'kulit sintetis',
      'pu leather',
      'suede',
      'fleece',
      'wool',
      'rajut',
      'knit',
      'kaos polos',
      'sablon',
      'bordir',
      'garmen',
      'konveksi',
      'penjahit',
      'vermak',
      'vermak levis',
      'potong celana',
      'kecilin baju',
      'ganti resleting',
      'payet',
      'furing',
      'lining',
    ],
    'Tagihan': [
      'listrik',
      'wifi',
      'internet',
      'pulsa',
      'bayar',
      'token',
      'pdam',
      'air',
      'indihome',
      'telkomsel',
      'kuota',
      'data',
      'langganan',
      'netflix',
      'spotify',
      'iuran',
      'bulanan',
      'tunggakan',
      'pajak',
      'pbb',
      'cicilan',
      'kredit',
      'angsuran',
      'pln',
      'biling',
      'topup',
      'tagihan',
      'indosat',
      'xl',
      'tri',
      'smartfren',
      'biznet',
      'myrepublic',
      'firstmedia',
      'tv kabel',
      'kredit motor',
      'kredit mobil',
      'cicil',
      'tenor',
      'admin',
      'biaya layanan',
      'iuran warga',
      'rt rw',
      'pajak motor',
      'stnk',
      'sim',
      'perpanjang',
      'denda',
      'pajak penghasilan',
      'pph',
      'ppn',
      'beacukai',
      'pajak bumi',
      'asuransi jiwa',
      'asuransi kesehatan',
      'premi',
      'jatuh tempo',
      'autodebet',
      'transfer bank',
      'biaya admin',
      'koding',
      'domain',
      'hosting',
      'server',
      'vps',
      'api key',
      'pembayaran',
      'kewajiban',
      'beban',
      'sewa',
      'kontrak',
      'deposit',
      'penalti',
      'bunga bank',
      'biaya langganan',
      'membership',
      'app store',
      'play store',
      'icloud',
      'google drive',
      'dropbox',
      'github',
      'adobe',
      'canva',
      'zoom',
      'office 365',
      'cloud storage',
      'vpn',
      'biaya parkir langganan',
      'iuran kebersihan',
      'iuran keamanan',
      'retribusi',
      'pln pascabayar',
      'pln prabayar',
      'pdam tirta',
      'air bersih',
      'air komunal',
      'iuran odf',
      'telkom',
      'telepon rumah',
      'speedy',
      'astranet',
      'mnc play',
      'cbn',
      'republic',
      'oxygen home',
      'xl home',
      'giga',
      'smartfren home',
      'mifi',
      'andromax',
      'orbit',
      'telkomsel orbit',
      'kuota internet',
      'paket data',
      'pulsa darurat',
      'pulsa transfer',
      'masa aktif',
      'kartu halo',
      'matrix',
      'xplor',
      'smartfren pascabayar',
      'pajak mobil',
      'bpkb',
      'mutasi kendaraan',
      'balik nama',
      'pajak tahunan',
      'pajak 5 tahunan',
      'plat nomor',
      'tnkb',
      'pajak progresif',
      'pajak reklame',
      'pajak restoran',
      'pb1',
      'pajak hotel',
      'pajak hiburan',
      'e-samsat',
      'samsat digital',
      'pbb-p2',
      'sppt pbb',
      'njop',
      'spt',
      'spt tahunan',
      'e-filing',
      'npwp',
      'pajak badan',
      'pph 21',
      'pph 22',
      'pph 23',
      'pph 25',
      'pph 4 ayat 2',
      'ppn masukan',
      'ppn keluaran',
      'faktur pajak',
      'e-faktur',
      'asuransi mobil',
      'asuransi motor',
      'asuransi properti',
      'asuransi kebakaran',
      'all risk',
      'tlo',
      'total loss only',
      'klaim asuransi',
      'deductible',
      'own damage',
      'cicilan rumah',
      'kpr',
      'kpa',
      'cicilan apartemen',
      'cicilan tanah',
      'pegadaian',
      'tebus gadai',
      'perpanjang gadai',
      'bunga gadai',
      'leasing',
      'fif',
      'adira',
      'oto',
      'baf',
      'wom',
      'mandiri utama finance',
      'muf',
      'bca finance',
      'acc',
      'taf',
      'indomobil finance',
      'kredit pintar',
      'akulaku',
      'kredivo',
      'spaylater',
      'gopaylater',
      'indodana',
      'julo',
      'home credit',
      'hci',
      'dana cicil',
      'paylater',
      'pinjol',
      'pinjaman online',
      'fintech',
      'p2p lending',
      'biaya penanganan',
      'bunga cicilan',
      'denda keterlambatan',
      'sewa rumah',
      'kontrakan',
      'sewa kos',
      'kosan',
      'kost',
      'sewa ruko',
      'sewa kios',
      'sewa lapak',
      'sewa apartemen',
      'maintenance fee',
      'service charge',
      'sinking fund',
      'iuran ipl',
      'iuran pengelolaan lingkungan',
      'iuran sampah',
      'iuran keamanan',
      'iuran sosial',
      'donasi rt',
      'iuran duka',
      'iuran agustusan',
      'iuran pkk',
      'iuran karang taruna',
      'membership gym',
      'celebrity fitness',
      'gold gym',
      'fitness first',
      'fit hub',
      'anytime fitness',
      'sanggar senam',
      'member renang',
      'langganan koran',
      'langganan majalah',
      'kompas',
      'langganan youtube premium',
      'youtube music',
      'apple music',
      'joox',
      'deezer',
      'tidal',
      'disney plus',
      'hotstar',
      'hbo go',
      'prime video',
      'amazon prime',
      'viu',
      'iqiyi',
      'wetv',
      'vidio',
      'vidio premier',
      'mola tv',
      'vision plus',
      'catchplay',
      'crunchyroll',
      'bilibili premium',
      'webtoon koin',
      'kakao page',
      'wattpad',
      'canva pro',
      'freepik premium',
      'shutterstock',
      'midjourney',
      'chatgpt plus',
      'openai api',
      'claude pro',
      'copilot pro',
      'notion plus',
      'zoom pro',
      'google workspace',
      'gsuite',
      'microsoft 365',
      'icloud storage',
      'onedrive',
      'dropbox plus',
      'mega nz',
      'hosting niagahoster',
      'hostinger',
      'rumahweb',
      'dewaweb',
      'idcloudhost',
      'domain id',
      'domain com',
      'domain net',
      'ssl certificate',
      'cloudflare',
      'aws',
      'amazon web services',
      'google cloud platform',
      'gcp',
      'azure',
      'digitalocean',
      'linode',
      'vultr',
      'firebase',
      'supabase',
      'vercel',
      'netlify',
      'heroku',
      'mailchimp',
      'sendgrid',
      'twilio',
      'midtrans',
      'xendit',
      'doku',
      'paypal verification',
      'cc fee',
      'chargeback',
      'biaya kliring',
      'rtgs',
      'bifast',
      'bi-fast',
      'biaya transfer interbank',
      'admin bank',
      'biaya bulanan atm',
      'pinalti saldo minimum',
      'dormant account fee',
    ],
    'Hiburan': [
      'bioskop',
      'nonton',
      'game',
      'topup',
      'diamond',
      'steam',
      'playstore',
      'konser',
      'wisata',
      'liburan',
      'tiket',
      'premium',
      'youtube',
      'karaoke',
      'playstation',
      'mabar',
      'netflix',
      'disney',
      'streaming',
      'taman',
      'rekreasi',
      'hobi',
      'buku novel',
      'event',
      'nonton film',
      'concert',
      'festival',
      'taman bermain',
      'dufan',
      'waterboom',
      'libur',
      'jalanjalan',
      'healing',
      'traveling',
      'kado',
      'hadiah',
      'gift',
      'voucher game',
      'mobile legends',
      'pubg',
      'genshin',
      'valorant',
      'minecraft',
      'roblox',
      'rdr2',
      'steam wallet',
      'xbox',
      'nintendo',
      'switch',
      'joycon',
      'headset',
      'controller',
      'joystick',
      'mouse gaming',
      'keyboard mechanical',
      'monitor',
      'vga',
      'gpu',
      'gaming',
      'esport',
      'turnamen',
      'match',
      'ranking',
      'skin',
      'battlepass',
      'item game',
      'gacha',
      'spin',
      'event konser',
      'tiket event',
      'parkir konser',
      'snack bioskop',
      'popcorn',
      'cola',
      'kaset',
      'cd',
      'dvd',
      'bluray',
      'vinyl',
      'komik',
      'majalah',
      'poster',
      'action figure',
      'diecast',
      'lego',
      'puzzle',
      'board game',
      'kartu',
      'billiard',
      'bowling',
      'ice skating',
      'paintball',
      'gokart',
      'flying fox',
      'camping',
      'hiking',
      'diving',
      'snorkeling',
      'surfing',
      'ski',
      'taman nasional',
      'museum',
      'galeri seni',
      'kebun binatang',
      'xxi',
      'cgv',
      'cinepolis',
      'imax',
      'the premiere',
      'velvet class',
      'gold class',
      '4dx',
      'satin',
      'tiket bioskop',
      'mtix',
      'cgv pay',
      'tix id',
      'popcorn caramel',
      'nachos',
      'hotdog bioskop',
      'java tea',
      'djakarta warehouse project',
      'dwp',
      'java jazz',
      'soundrenaline',
      'pestapora',
      'synchronize',
      'wtf',
      'we the fest',
      'konser kpop',
      'konser coldplay',
      'promotor',
      'pk entertainment',
      'ime indonesia',
      'dyandra',
      'ismaya',
      'ticketmaster',
      'loketcom',
      'tiketcom',
      'traveloka xperience',
      'klook',
      'ancol',
      'taman mini',
      'tmii',
      'ragunan',
      'monas',
      'parangtritis',
      'kuta',
      'ubud',
      'seminyak',
      'canggu',
      'nusapenida',
      'labuan bajo',
      'komodo',
      'raja ampat',
      'bunaken',
      'derawan',
      'wakatobi',
      'bromo',
      'kawah ijen',
      'dieng',
      'borobudur',
      'prambanan',
      'tanah lot',
      'uluwatu',
      'tangkuban perahu',
      'ciwidey',
      'lembang',
      'puncak',
      'bogor',
      'carita',
      'anyer',
      'pariangan',
      'danau toba',
      'samosir',
      'bukittinggi',
      'belitung',
      'tanjung tinggi',
      'derawan',
      'kakaban',
      'maratua',
      'karimunjawa',
      'batu malang',
      'jatim park',
      'museum angkut',
      'eco green park',
      'predator fun park',
      'bns',
      'malang night paradise',
      'selecta',
      'santerra',
      'flora wisata',
      'trans studio',
      'bandung',
      'makassar',
      'cibubur',
      'kidzania',
      'seaworld',
      'ocean dream',
      'samudra',
      'atlantis',
      'waterpark',
      'snowbay',
      'jogja bay',
      'waterbom bali',
      'go wet',
      'the jungle',
      'jungleland',
      'saloka',
      'wisata alam',
      'glamping',
      'camping ground',
      'tenda',
      'sleeping bag',
      'matras',
      'carrier',
      'nesting',
      'kompor camping',
      'gas kaleng',
      'flysheet',
      'hammock',
      'headlamp',
      'senter',
      'tracking pole',
      'sepatu gunung',
      'sandal gunung',
      'carrier bag',
      'raincover',
      'daypack',
      'buku fiksi',
      'novel',
      'manga',
      'manhwa',
      'manhua',
      'light novel',
      'ln',
      'action figure anime',
      'nendoroid',
      'figma',
      'shf',
      'bandai',
      'kotobukiya',
      'good smile company',
      'hot toys',
      'funko pop',
      'gundam',
      'gunpla',
      'high grade',
      'hg',
      'real grade',
      'rg',
      'master grade',
      'mg',
      'perfect grade',
      'pg',
      'sd gundam',
      'tamiya',
      'mini 4wd',
      'kit tamiya',
      'dinamo tamiya',
      'baterai tamiya',
      'track tamiya',
      'hot wheels',
      'tomica',
      'matchbox',
      'majorette',
      'greenlight',
      'jada',
      'diecast mobil',
      'diecast motor',
      'diecast pesawat',
      'lego creator',
      'lego technic',
      'lego city',
      'lego star wars',
      'lego ninjago',
      'lego friends',
      'lego mindstorms',
      'brick',
      'nanoblock',
      'block',
      'puzzle 1000 pcs',
      'rubik',
      'rubik 3x3',
      'rubik 4x4',
      'rubik 5x5',
      'monopoli',
      'ludo',
      'ular tangga',
      'scrabble',
      'uno',
      'uno stacko',
      'uno cards',
      'kartu remi',
      'kartu gaple',
      'domino',
      'poker',
      'werewolf',
      'exploding kittens',
      'avalon',
      'catan',
      'ticket to ride',
      'dixit',
      'carcassonne',
      'splendor',
      '7 wonders',
      'dungeons and dragons',
      'dnd',
      'board game cafe',
      'strikeball',
      'airsoft',
      'airsoft gun',
      'bb bullet',
      'paintball gear',
      'gokart racing',
      'billiard club',
      'stik billiard',
      'kapur billiard',
      'chico',
      'futsal hobi',
      'badminton hobi',
      'raket badminton',
      'senar raket',
      'shuttlecock',
      'kok',
      'sepatu badminton',
      'sepatu futsal',
      'sepatu basket',
      'bola basket',
      'bola futsal',
      'bola sepak',
      'glove kiper',
      'deker',
      'jersey bola',
      'sepeda',
      'sepeda lipat',
      'seli',
      'sepeda balap',
      'roadbike',
      'sepeda gunung',
      'mtb',
      'bmx',
      'fixie',
      'helm sepeda',
      'sarung tangan sepeda',
      'jersey sepeda',
      'celana padding',
      'pompa sepeda',
      'lampu sepeda',
      'tas sepeda',
      'gembok sepeda',
      'speedometer sepeda',
      'trainer sepeda',
      'skateboard',
      'deck',
      'truck skateboard',
      'wheels skateboard',
      'bearing skateboard',
      'griptape',
      'sepatu skate',
      'longboard',
      'cruiserboard',
      'pennyboard',
      'fingerboard',
      'tech deck',
      'inline skate',
      'roller skate',
      'aggressive skate',
      'slalom skate',
      'speed skate',
      'quad skate',
      'helm skate',
      'pelindung lutut',
      'pelindung siku',
      'wrist guard',
      'fishing',
      'joran',
      'reel',
      'senar pancing',
      'kail',
      'umpan',
      'lure',
      'floater',
      'pelampung pancing',
      'box pancing',
      'tas joran',
      'umpan hidup',
      'pelet',
      'essen',
      'matapancing',
      'swivel',
      'snaps',
      'leader line',
      'fluorocarbon',
      'baju mancing',
      'topi mancing',
      'perahu mancing',
      'sewa kapal mancing',
      'kolam pemancingan',
      'galatama',
      'harian',
      'kiloan',
      'mancing mania',
      'aquarium',
      'aquascape',
      'ikan hias',
      'cupang',
      'guppy',
      'koi',
      'arowana',
      'louhan',
      'discus',
      'maskoki',
      'aquarium tank',
      'filter aquarium',
      'aerator',
      'lampu aquascape',
      'tanaman air',
      'co2 system',
      'pasir malang',
      'soil',
      'pupuk dasar',
      'pupuk cair',
      'pinset aquascape',
      'gunting aquascape',
      'pakan ikan',
      'pellet ikan',
      'cacing sutra',
      'kutu air',
      'artemia',
      'udang hias',
      'keong tanduk',
      'channa',
      'predator fish',
      'reptil',
      'ular',
      'kadal',
      'gecko',
      'iguana',
      'kura-kura',
      'torto',
      'turtle',
      'aquaterrarium',
      'terrarium',
      'kandang reptil',
      'lampu uva uvb',
      'basking lamp',
      'substrate',
      'cocopeat',
      'perlite',
      'pakan reptil',
      'jangkrik',
      'ulat hongkong',
      'ulat jerman',
      'pinkies',
      'mencit',
      'burung kicau',
      'murai batu',
      'lovebird',
      'kenari',
      'kacer',
      'cucak ijo',
      'pleci',
      'kandang burung',
      'sangkar',
      'pakan burung',
      'voert',
      'milet',
      'extrafooding',
      'ef',
      'kroto',
      'jangkrik burung',
      'vitamin burung',
      'gantangan',
      'lomba burung',
      'kucing',
      'persia',
      'anggora',
      'british shorthair',
      'bsh',
      'ragdoll',
      'maine coon',
      'sphynx',
      'kucing kampung',
      'domestik',
      'makanan kucing',
      'cat food',
      'wet food',
      'dry food',
      'whiskas',
      'royal canin',
      'pro plan',
      'me-o',
      'bolt',
      'felibite',
      'snack kucing',
      'ciao churu',
      'creamy treat',
      'pasir kucing',
      'cat litter',
      'bentonite',
      'pasir gumpal',
      'zeolit',
      'tofu litter',
      'serutan kayu',
      'pet cargo',
      'tas kucing',
      'kandang kucing',
      'cat condo',
      'cat tree',
      'garukan kucing',
      'scratching post',
      'mainan kucing',
      'laser pointer',
      'catnip',
      'shampoo kucing',
      'grooming kucing',
      'sisir kucing',
      'gunting kuku kucing',
      'susu kucing',
      'vitamin kucing',
      'obat cacing kucing',
      'obat kutu kucing',
      'frontline',
      'advocate',
      'revolution',
      'anjing',
      'poodle',
      'pomeranian',
      'pom',
      'chihuahua',
      'shih tzu',
      'maltese',
      'pug',
      'french bulldog',
      'beagle',
      'golden retriever',
      'labrador',
      'german shepherd',
      'husky',
      'samoyed',
      'alaskan malamute',
      'chow chow',
      'rottweiler',
      'pitbull',
      'makanan anjing',
      'dog food',
      'royal canin dog',
      'pro plan dog',
      'pedigree',
      'alpo',
      'snack anjing',
      'dog treat',
      'tulang-tulangan',
      'tali tuntun',
      'leash',
      'collar',
      'harness',
      'muzzle',
      'kandang anjing',
      'pet bed',
      'kasur anjing',
      'shampoo anjing',
      'grooming anjing',
      'pampers anjing',
      'underpad',
      'mainan anjing',
      'bola anjing',
      'frisbee',
      'vitamin anjing',
      'obat kutu anjing',
      'bravecto',
      'nexgard',
      'simparica',
      'klinik hewan',
      'dokter hewan',
      'vet',
      'pet shop',
      'pet hotel',
      'pet cafe',
      'titip hewan',
      'penitipan kucing',
      'penitipan anjing',
      'buku hewan',
      'majalah hewan',
      'pameran hewan',
      'pet expo',
    ],
    'Pendidikan': [
      'buku',
      'kursus',
      'kuliah',
      'dosen',
      'tugas',
      'alat tulis',
      'atk',
      'spp',
      'bimbel',
      'pelatihan',
      'seminar',
      'workshop',
      'skripsi',
      'bimbingan',
      'fotocopy',
      'printer',
      'tinta',
      'laptop',
      'kursus bahasa',
      'les',
      'ujian',
      'praktikum',
      'wisuda',
      'labtop',
      'mouse',
      'keyboard',
      'meja belajar',
      'kursi',
      'tas sekolah',
      'seragam',
      'ujian nasional',
      'bayar kuliah',
      'uangkuliah',
      'buku cetak',
      'modul',
      'jurnal',
      'kertas',
      'pulpen',
      'penggaris',
      'buku tulis',
      'buku gambar',
      'pensil',
      'penghapus',
      'rautan',
      'jangka',
      'buku catatan',
      'map',
      'binder',
      'lakban',
      'stapler',
      'klip',
      'kalkulator',
      'kamus',
      'ensiklopedia',
      'karya ilmiah',
      'tesis',
      'disertasi',
      'proposal',
      'praktek',
      'pembayaran spp',
      'sumbangan sekolah',
      'biaya buku',
      'biaya seragam',
      'biaya praktikum',
      'biaya wisuda',
      'lab bahasa',
      'lab komputer',
      'perpustakaan',
      'denda perpustakaan',
      'tutor',
      'pendidikan',
      'pelatihan sertifikasi',
      'toefl',
      'ielts',
      'kursus coding',
      'bootcamp',
      'webinar',
      'tutorial',
      'elearning',
      'zoom kelas',
      'gmeet',
      'materi',
      'tugas akhir',
      'referensi',
      'e-book',
      'software pendidikan',
      'lisensi edukasi',
      'biaya pendaftaran',
      'biaya formulir',
      'uang gedung',
      'biaya praktikum',
      'biaya almamater',
      'unpam',
      'universitas pamulang',
      'kampus',
      'kartu mahasiswa',
      'ktm',
      'reguler a',
      'reguler b',
      'reguler c',
      'uts',
      'uas',
      'her',
      'semester short',
      'sp',
      'semester pendek',
      'krs',
      'khs',
      'ipk',
      'ip',
      'transkrip',
      'ijazah',
      'legalisir',
      'toga',
      'baju wisuda',
      'foto wisuda',
      'plakat',
      'selempang wisuda',
      'gordon',
      'undangan wisuda',
      'sidang skripsi',
      'sidang proposal',
      'sempro',
      'komprehensif',
      'revisi skripsi',
      'jilid skripsi',
      'hardcover skripsi',
      'print tugas',
      'print warna',
      'jilid lakban',
      'jilid spiral',
      'kertas hvs',
      'a4',
      'f4',
      'kuarto',
      'kertas buffalo',
      'kertas mika',
      'pulpen gel',
      'pilot',
      'hi-tech',
      'standard',
      'my gel',
      'ballpoint',
      'pensil 2b',
      'faber castell',
      'steadler',
      'lyra',
      'penghapus joyko',
      'tipex',
      'tipp-ex',
      'tipex kertas',
      'tipex cair',
      'penggaris besi',
      'penggaris plastik',
      'busur derajat',
      'jangka matematika',
      'buku saku',
      'sticky notes',
      'post it',
      'highlighter',
      'stabilo',
      'stabilo boss',
      'marker',
      'spidol whiteboard',
      'snowman',
      'spidol permanen',
      'papan tulis',
      'whiteboard',
      'blackboard',
      'kapur tulis',
      'penghapus papan',
      'rautan meja',
      'cutter',
      'gunting atk',
      'double tape',
      'solasi',
      'lakban hitam',
      'lakban bening',
      'staples',
      'isi staples',
      'paper clip',
      'penjepit kertas',
      'binder clip',
      'puncher',
      'pembolong kertas',
      'map snelhechter',
      'map l',
      'map tali',
      'map plastik',
      'papan ujian',
      'clipboard',
      'kalkulator ilmiah',
      'scientific calculator',
      'casio',
      'fx-991es',
      'kamus bahasa inggris',
      'kamus lengkap',
      'kamus oxford',
      'gramedia',
      'gunung agung',
      'toko buku',
      'buku bekas',
      'kwitang',
      'buku bajakan',
      'buku kuliah',
      'textbook',
      'e-book kuliah',
      'pdf kuliah',
      'jurnal scopus',
      'ieee',
      'sciencedirect',
      'springer',
      'google scholar',
      'mendeley',
      'zotero',
      'turnitin',
      'cek plagiasi',
      'parafraase',
      'jasa skripsi',
      'jasa ketik',
      'jasa translate',
      'kursus bahasa inggris',
      'ef',
      'english first',
      'lia',
      'ilp',
      'wall street english',
      'kampung inggris',
      'pare',
      'les privat',
      'kumon',
      'ganesha operation',
      'go',
      'primagama',
      'bintang pelajar',
      'zenius',
      'ruangguru',
      'pahamify',
      'dicoding',
      'bwa',
      'buildwithangga',
      'udemy',
      'coursera',
      'edx',
      'linkedin learning',
      'skilvul',
      'hacktiv8',
      'purwadhika',
      'binar academy',
      'digitalent',
      'kominfo',
      'sertifikasi oracle',
      'ccna',
      'cisco',
      'mikrotik',
      'mtcna',
      'aws certified',
      'gcp certified',
      'ceh',
      'certified ethical hacker',
      'comptia',
      'itil',
      'pmp',
      'scrum master',
      'toefl itp',
      'toefl ibt',
      'toeic',
      'ielts akademis',
      'ielts umum',
      'british council',
      'idp',
      'ielts test fee',
      'biaya ujian toefl',
      'simulasi toefl',
      'tryout',
      'toefl preparation',
      'ielts preparation',
      'gmat',
      'gre',
      'tpa',
      'bappenas',
      'tes potensi akademik',
      'snbt',
      'utbk',
      'simak ui',
      'utul ugm',
      'smup unpad',
      'pendaftaran kuliah',
      'uang pangkal',
      'uang gedung',
      'dana pengembangan',
      'bpp',
      'ukt',
      'uang kuliah tunggal',
      'ukt kelompok',
      'krs online',
      'sia',
      'siakad',
      'portal kampus',
      'lms',
      'e-learning kampus',
      'moodle',
      'google classroom',
      'microsoft teams',
      'zoom edukasi',
      'akun belajar',
      'email kampus',
      'student email',
      'kartu perpustakaan',
      'buku perpus',
      'pinjam buku',
      'perpanjang buku perpus',
      'denda perpus',
      'skripsi perpus',
      'ruang baca',
      'digital library',
      'digilib',
      'e-journal kampus',
      'akses jurnal',
      'jasa jilid',
      'jasa cetak banner',
      'cetak poster tumpeng',
      'id card panitia',
      'tali lanyard panitia',
      'seragam panitia',
      'jaket himpunan',
      'jaket angkatan',
      'korsa',
      'pdh',
      'pdl',
      'almamater',
      'almet',
      'kancing almet',
      'topi wisuda',
      'baju toga',
      'kalung gordon',
      'medali wisuda',
      'ijazah asli',
      'skpi',
      'surat keterangan pendamping ijazah',
      'legalisir ijazah',
      'legalisir transkrip',
      'ijazah d3',
      'ijazah s1',
      'ijazah s2',
      'ijazah s3',
      'profesi',
      'koas',
      'ppds',
      'magister',
      'doktor',
      'pascasarjana',
    ],
    'Perawatan': [
      'salon',
      'potong rambut',
      'skincare',
      'makeup',
      'facial',
      'lulur',
      'barbershop',
      'perawatan',
      'kosmetik',
      'parfum',
      'kecantikan',
      'cukur',
      'spa',
      'creambath',
      'manicure',
      'pedicure',
      'grooming',
      'sabun wajah',
      'toner',
      'serum',
      'masker wajah',
      'haircut',
      'smoothing',
      'coloring',
      'cat rambut',
      'peeling',
      'body lotion',
      'pelembab',
      'foundation',
      'lipstik',
      'mascara',
      'eyeliner',
      'bedak',
      'cleanser',
      'micellar water',
      'sunscreen',
      'sabun mandi',
      'shampo',
      'kondisioner',
      'masker rambut',
      'minyak rambut',
      'pomade',
      'gel rambut',
      'cat kuku',
      'nail art',
      'lulur badan',
      'masker badan',
      'pembersih wajah',
      'obat jerawat',
      'krim malam',
      'krim siang',
      'pelembab bibir',
      'lip balm',
      'blush on',
      'eyeshadow',
      'penjepit bulu mata',
      'kuas makeup',
      'spons makeup',
      'pembersih makeup',
      'kapas',
      'cukur jenggot',
      'aftershave',
      'peeling wajah',
      'scrub',
      'masker bibir',
      'eyelash extension',
      'tanam bulu mata',
      'sulam alis',
      'tato',
      'tindik telinga',
      'pijat refleksi',
      'pijat lulur',
      'sauna',
      'totok wajah',
      'perawatan kuku',
      'nail polish',
      'penghapus kutek',
      'ixobox',
      'captain barbershop',
      'kaizen',
      'hairstylist',
      'potong poni',
      'wash and blow',
      'cuci catok',
      'styling rambut',
      'rebonding',
      'perming',
      'keriting rambut',
      'hair extension',
      'sambung rambut',
      'hair spa',
      'hair mask',
      'hair serum',
      'hair tonic',
      'obat anti botak',
      'minoxidil',
      'finasteride',
      'shampoo anti ketombe',
      'selsun',
      'ketomed',
      'head and shoulders',
      'clear',
      'pantene',
      'sunsilk',
      'dove',
      'loreal',
      'tresemme',
      'matrix',
      'makarizo',
      'hair vitamin',
      'ellips',
      'lucido-e',
      'pomade oil based',
      'pomade water based',
      'clay rambut',
      'wax rambut',
      'hair spray',
      'gatsbby',
      'gatsby',
      'suavecito',
      'murrays',
      'smith',
      'barber',
      'pencukur jenggot',
      'pisau cukur',
      'gillette',
      'schick',
      'clippers',
      'trimmer',
      'shaving cream',
      'shaving foam',
      'aftershave lotion',
      'pencukur bulu hidung',
      'pinset bulu',
      'waxing',
      'waxing kit',
      'sugar wax',
      'mirael',
      'strip wax',
      'ipl hair removal',
      'laser hair removal',
      'underarm waxing',
      'brazilian waxing',
      'skincare lokal',
      'somethinc',
      'scarlett',
      'whitelab',
      'avoskin',
      'wardah',
      'kahf',
      'ms glow',
      'erha',
      'hanya',
      'hanyul',
      'skincare korea',
      'cosrx',
      'innisfree',
      'laneige',
      'sulwhasoo',
      'the face shop',
      'nature republic',
      'aloe vera gel',
      'skincare jepang',
      'hada labo',
      'skintific',
      'originote',
      'glad2glow',
      'bioaqua',
      'anessa',
      'biore',
      'sunscreen skin aqua',
      'sunscreen cetaphil',
      'sunscreen emina',
      'sunscreen garnier',
      'garnier micellar water',
      'bioderma',
      'nivea',
      'vaseline',
      'body serum',
      'body butter',
      'body scrub',
      'sinzui',
      'shinzui',
      'citra',
      'marina',
      'viva',
      'viva air mawar',
      'viva milk cleanser',
      'face wash',
      'facial foam',
      'facial cleanser',
      'cleansing oil',
      'cleansing balm',
      'double cleansing',
      'exfoliating toner',
      'hydrating toner',
      'essence',
      'serum retinol',
      'serum vitamin c',
      'serum niacinamide',
      'serum hyaluronic acid',
      'serum aha bha',
      'serum jerawat',
      'acne patch',
      'derma angel',
      'cosrx acne patch',
      'obat jerawat totol',
      'benzolac',
      'vitacid',
      'acnemed',
      'moisturizer',
      'pelembab wajah',
      'sheet mask',
      'clay mask',
      'peel off mask',
      'eye cream',
      'eye patch',
      'lip serum',
      'lip mask',
      'lip scrub',
      'lip balm tendercare',
      'oriflame',
      'lipstik wardah',
      'maybelline',
      'lip tint',
      'lip cream',
      'lip matte',
      'lip gloss',
      'lip liner',
      'foundation wardah',
      'bb cream',
      'cc cream',
      'dd cream',
      'cushion',
      'cushion skintific',
      'concealer',
      'loose powder',
      'bedak tabur',
      'compact powder',
      'bedak padat',
      'two way cake',
      'blush on cushion',
      'highlighter powder',
      'contouring',
      'shading',
      'eyebrow pencil',
      'pensil alis',
      'eyebrow gel',
      'mascara waterproof',
      'eyeliner pen',
      'eyeliner gel',
      'eyeshadow palette',
      'setting spray',
      'makeup remover',
      'kapas wajah',
      'selection',
      'kapas tipis',
      'beauty blender',
      'brush set',
      'kuas eyeshadow',
      'kuas foundation',
      'eyelash curler',
      'bulu mata palsu',
      'lem bulu mata',
      'parfum designer',
      'parfum lokal',
      'hmns',
      'onix',
      'saff n co',
      'parfum miniso',
      'zara parfum',
      'parfum cowok',
      'parfum cewek',
      'edp',
      'edt',
      'edc',
      'body mist',
      'cologne',
      'fragrance oil',
      'deodorant',
      'rexona',
      'axe',
      'nivea deo',
      'deodorant spray',
      'tawas',
      'deodorant alami',
      'spa paketan',
      'massage oil',
      'minyak zaitun mustika ratu',
      'lulur purbasari',
      'lulur herborist',
      'bath bomb',
      'garam mandi',
      'bath salt',
      'bubble bath',
      'body wash',
      'sabun cair',
      'biore body wash',
      'lifebuoy',
      'dettol',
      'lux',
      'dove body wash',
      'sabun batang',
      'sabun sulfur',
      'jf sulfur',
      'sabun bayi untuk wajah',
      'facial treatment',
      'microdermabrasion',
      'chemical peeling',
      'laser glowing',
      'pico laser',
      'hifu',
      'rf',
      'radio frequency',
      'setrika wajah',
      'clinic beauty',
      'erha clinic',
      'zap',
      'zap clinic',
      'miracle clinic',
      'natasha',
      'larissa',
      'bamed',
      'derma',
      'dermaster',
      'facia',
    ],
    'Rumah Tangga': [
      'sabun',
      'shampoo',
      'pasta gigi',
      'cuci',
      'kebersihan',
      'sapu',
      'pel',
      'ember',
      'perabot',
      'dapur',
      'alat mandi',
      'deterjen',
      'pewangi',
      'tisu',
      'lampu',
      'renovasi',
      'kulkas',
      'kompor',
      'piring',
      'gelas',
      'seprei',
      'handuk',
      'bantal',
      'gorden',
      'cat',
      'pembersih',
      'spons',
      'clink',
      'panci',
      'wajan',
      'spatula',
      'cangkir',
      'sendok',
      'garpu',
      'keset',
      'hanger',
      'jemuran',
      'rak',
      'kamar mandi',
      'lantai',
      'dinding',
      'atap',
      'kunci',
      'engsel',
      'baut',
      'paku',
      'palu',
      'obeng',
      'tang',
      'bor',
      'gergaji',
      'isolasi',
      'kabel',
      'colokan',
      'stop kontak',
      'saklar',
      'fiting',
      'bohlam',
      'tangga',
      'sapu lidi',
      'sikat',
      'pel lantai',
      'cairan pembersih',
      'karbol',
      'pelembut pakaian',
      'pemutih',
      'hanger baju',
      'penjepit baju',
      'tempat sampah',
      'kantong plastik',
      'tisu toilet',
      'tisu basah',
      'keranjang',
      'lemari',
      'meja',
      'kursi',
      'kasur',
      'bantal',
      'guling',
      'selimut',
      'sprei',
      'korden',
      'karpet',
      'keset kaki',
      'gayung',
      'bak air',
      'filter air',
      'selang',
      'keran',
      'shower',
      'wastafel',
      'kloset',
      'cermin',
      'rak piring',
      'kompor gas',
      'gas lpg',
      'regulator gas',
      'blender',
      'magic com',
      'microwave',
      'oven',
      'dispenser',
      'galon',
      'pompa air',
      'pompa galon',
      'rinso',
      'daia',
      'attack',
      'so klin',
      'boom',
      'deterjen cair',
      'deterjen bubuk',
      'molto',
      'downy',
      'pelembut',
      'pewangi pakaian',
      'soklin lantai',
      'super pell',
      'wipol',
      'proclin',
      'bayclin',
      'vanish',
      'sunlight',
      'mama lemon',
      'sabun cuci piring',
      'spons cuci piring',
      'kawat cuci piring',
      'mama lime',
      'harpic',
      'bebek kloset',
      'pembersih kamar mandi',
      'vixal',
      'porstex',
      'stella',
      'glade',
      'pewangi ruangan',
      'kapur barus',
      'bagus',
      'kamper',
      'tisu paseo',
      'tisu nice',
      'tisu tessa',
      'tisu kering',
      'tisu dapur',
      'lampu led',
      'philips',
      'hannochs',
      'panasonic',
      'lampu pijar',
      'fitting lampu',
      'steker',
      'colokan t',
      'stopkontak arde',
      'kabel roll',
      'kabel engkel',
      'isolasi listrik',
      'solasi hitam',
      'semprotan nyamuk',
      'baygon',
      'vape',
      'hit',
      'obat nyamuk bakar',
      'obat nyamuk elektrik',
      'kamper lemari',
      'perangkap tikus',
      'lem tikus',
      'racun tikus',
      'racun semut',
      'kapur ajaib',
      'sapu ijuk',
      'sapu nilon',
      'alat pel spin mop',
      'kain pel refil',
      'pengki',
      'serokan',
      'kemoceng',
      'kemoceng bulu ayam',
      'sikat lantai',
      'sikat wc',
      'plunger',
      'sedot wc',
      'gayung mandi',
      'bak mandi lipat',
      'tirai kamar mandi',
      'gantungan handuk',
      'tempat sabun',
      'dispenser sabun',
      'sikat gigi',
      'pepsodent',
      'ciptadent',
      'close up',
      'formula',
      'sensodyne',
      'colgate',
      'pasta gigi herbal',
      'mouthwash',
      'listerine',
      'betadine kumur',
      'shampoo sunsilk',
      'clear',
      'pantene',
      'dove',
      'shampoo cair',
      'shampoo sachet',
      'sabun lifebuoy',
      'dettol',
      'lux',
      'biore',
      'sabun batang',
      'sabun cair refil',
      'shower puff',
      'handuk mandi',
      'handuk wajah',
      'handuk kecil',
      'lemari pakaian',
      'lemari plastik',
      'napolly',
      'lemari laci',
      'gantungan baju',
      'hanger plastik',
      'hanger kawat',
      'rak baju',
      'rak jilbab',
      'kotak penyimpanan',
      'storage box',
      'container box',
      'meja kerja',
      'meja belajar',
      'meja lipat',
      'kursi kerja',
      'kursi kantor',
      'kursi plastik',
      'kursi bakso',
      'sofa',
      'bean bag',
      'kasur busa',
      'kasur springbed',
      'inoac',
      'kasur lipat',
      'kasur angin',
      'bantal dacron',
      'bantal bulu angsa',
      'guling dacron',
      'sarung bantal',
      'sarung guling',
      'sprei polos',
      'sprei kintakun',
      'sprei bonita',
      'bedcover',
      'selimut bulu',
      'selimut katun',
      'gorden jendela',
      'gorden pintu',
      'tirai magnet',
      'karpet bulu',
      'karpet plastik',
      'karpet karakter',
      'tikar',
      'tikar lipat',
      'keset mie',
      'keset kain',
      'keset diatoms',
      'piring keramik',
      'piring plastik',
      'piring melamin',
      'mangkok soto',
      'mangkok bakso',
      'gelas kaca',
      'gelas plastik',
      'cangkir kopi',
      'mug',
      'tumbler',
      'thermos',
      'termos air panas',
      'sendok makan',
      'garpu makan',
      'sendok teh',
      'sendok garpu set',
      'pisau dapur',
      'pisau daging',
      'pisau buah',
      'gunting dapur',
      'talenan',
      'talenan kayu',
      'talenan plastik',
      'wajan teflon',
      'wajan penggorengan',
      'panci sup',
      'panci mie',
      'panci presto',
      'dandang',
      'kukusan',
      'spatula kayu',
      'spatula silikon',
      'sutil',
      'serok gorengan',
      'capitan makanan',
      'pembuka kaleng',
      'pembuka botol',
      'ulekan',
      'cobek',
      'cobek batu',
      'cobek kayu',
      'parutan',
      'parutan keju',
      'saringan teh',
      'saringan minyak',
      'kocokan telur',
      'whisk',
      'cetakan es',
      'cetakan agar',
      'nampan',
      'baki',
      'tudung saji',
      'kain lap',
      'lap serbet',
      'lap microfiber',
      'celemek dapur',
      'apron',
      'sarung tangan oven',
      'cempal',
      'jepit piring panas',
      'timbangan kue',
      'timbangan dapur',
      'gelas ukur',
      'sendok ukur',
      'loyang kue',
      'cetakan puding',
      'kuas kue',
      'roller pin',
      'penggiling adonan',
      'botol kecap',
      'botol saos',
      'toples',
      'toples kaca',
      'toples plastik',
      'calista',
      'tupperware',
      'rantang',
      'lunch box',
      'kotak makan',
      'tas bekal',
      'botol minum',
      'kulkas 1 pintu',
      'kulkas 2 pintu',
      'freezer',
      'showcase',
      'mesin cuci',
      'mesin cuci 1 tabung',
      'mesin cuci 2 tabung',
      'front loading',
      'top loading',
      'setrika',
      'setrika uap',
      'meja setrika',
      'papan setrika',
      'jemuran baju aluminium',
      'jemuran handuk',
      'hanger jepit',
      'kipas angin',
      'kipas angin berdiri',
      'kipas angin dinding',
      'kipas angin meja',
      'ac',
      'air conditioner',
      'air cooler',
      'air purifier',
      'humidifier',
      'diffuser',
      'essential oil',
      'tv',
      'televisi',
      'smart tv',
      'android tv',
      'set top box',
      'stb',
      'antena tv',
      'bracket tv',
      'home theater',
      'speaker aktif',
      'soundbar',
      'dvd player',
      'kabel hdmi',
      'kabel rca',
      'remot tv',
      'remot ac',
      'baterai',
      'alkaline',
      'energizer',
      'baterai aaa',
      'baterai aa',
      'baterai kancing',
      'baterai charge',
      'charger hp',
      'kabel data',
      'powerbank',
      'stop kontak timer',
      'alarm',
      'jam weker',
      'hiasan dinding',
      'kaligrafi',
      'lukisan',
      'wallpaper dinding',
      'wall sticker',
      'foam brick',
      'stiker kompor',
      'stiker kulkas',
      'taplak meja',
      'sarung galon',
      'sarung kulkas',
      'sarung magic com',
      'cover mesin cuci',
      'cover tv',
      'cover kipas',
      'cover sofa',
      'vas bunga',
      'bunga plastik',
      'tanaman hias',
      'pot tanaman',
      'pot gantung',
      'rak bunga',
      'pupuk tanaman',
      'tanah humus',
      'sekop mini',
      'selang air',
      'semprotan tanaman',
      'sprayer',
      'kandang burung',
      'pakan burung',
      'aquarium',
      'pakan ikan',
      'kandang kucing',
      'pasir kucing',
      'makanan kucing',
      'whiskas',
      'royal canin',
      'makanan anjing',
      'pedigree',
      'kalung kucing',
      'shampoo kucing',
      'gembok',
      'gembok alarm',
      'kunci pintu',
      'handle pintu',
      'engsel pintu',
      'gerendel',
      'slot pintu',
      'door closer',
      'door stop',
      'penahan pintu',
      'paku payung',
      'paku beton',
      'baut roofing',
      'sekrup',
      'mur',
      'ring',
      'fisher',
      'dextone',
      'lem alteco',
      'lem korea',
      'lem aibon',
      'lem fox',
      'lem tembak',
      'lem pipa',
      'lem lilin',
      'isi lem tembak',
      'lakban kain',
      'double tape 3m',
      'meteran',
      'waterpas',
      'kunci pas',
      'kunci ring',
      'kunci inggris',
      'kunci L',
      'obeng plus',
      'obeng minus',
      'obeng tespen',
      'tang kombinasi',
      'tang potong',
      'tang lancip',
      'palu kambing',
      'palu karet',
      'gergaji kayu',
      'gergaji besi',
      'mata bor',
      'mesin bor',
      'mesin gerinda',
      'mata gerinda',
      'amplas',
      'kabel ties',
      'pipa pvc',
      'sambungan kran',
      'sambungan pipa',
      'knee',
      'tee',
      'dop',
      'seal tape',
      'seng',
      'asbes',
      'genteng',
      'cat tembok',
      'cat kayu',
      'cat besi',
      'thinner',
      'kuas cat',
      'roll cat',
      'bak cat',
      'dempul',
      'semen',
      'semen putih',
      'pasir',
      'batu bata',
      'batako',
      'hebel',
      'keramik lantai',
      'keramik dinding',
      'granit',
    ],
  };

  /// Ekstraksi nilai uang dari teks, mendukung angka ribuan dengan titik
  /// dan kata kunci 'ribu' serta 'juta'.
  static double? extractAmount(String text) {
    String lower = text.toLowerCase();

    // Pattern: mencari angka yang bisa memiliki titik pemisah atau koma desimal,
    // lalu diikuti opsional spasi dan kata 'ribu'/'juta'.
    RegExp regExp = RegExp(r'(\d+([.,]\d+)?)\s*(ribu|juta)?');
    Iterable<RegExpMatch> matches = regExp.allMatches(lower);

    if (matches.isEmpty) {
      // Fallback untuk slang uang
      if (lower.contains('gocap')) return 50000;
      if (lower.contains('cepek')) return 100000;
      if (lower.contains('goceng')) return 5000;
      if (lower.contains('seceng') || lower.contains('ceng')) return 1000;
      if (lower.contains('gopek')) return 500;
      return null;
    }

    double maxAmount = 0.0;

    for (var match in matches) {
      String numStr = match.group(1)!.replaceAll(',', '.');

      // Jika angka seperti "15.000", dart akan memparsenya sebagai 15.0
      // Padahal itu bisa jadi 15 ribu bulat.
      if (numStr.contains('.') && numStr.split('.').last.length == 3) {
        numStr = numStr.replaceAll('.', '');
      }

      double amount = double.tryParse(numStr) ?? 0.0;
      String? multiplier = match.group(3);

      if (multiplier == 'ribu') {
        amount *= 1000;
      } else if (multiplier == 'juta') {
        amount *= 1000000;
      } else {
        // Fallback: jika multiplier terpisah jauh, contoh: "kopi 15 untuk besok ribu"
        if (amount < 1000) {
          if (lower.contains('ribu')) {
            amount *= 1000;
          } else if (lower.contains('juta'))
            amount *= 1000000;
        }
      }

      if (amount > maxAmount) {
        maxAmount = amount;
      }
    }

    return maxAmount > 0 ? maxAmount : null;
  }

  /// Mendeteksi kategori transaksi dengan mencocokkan kata dalam input
  /// ke kamus mapping (_rules).
  static String detectCategory(String text) {
    String lower = text.toLowerCase();

    for (var entry in _rules.entries) {
      for (var keyword in entry.value) {
        if (lower.contains(keyword.toLowerCase())) {
          return entry.key;
        }
      }
    }

    return 'Lainnya'; // Default
  }

  /// Fungsi utama untuk mem-parse input suara mentah
  /// menjadi structured Map siap pakai
  static Map<String, dynamic> parseVoiceInput(String text) {
    String lower = text.toLowerCase();

    double? amount = extractAmount(lower);
    if (amount == null || amount <= 0) {
      throw Exception("Nominal uang tidak terdengar dengan jelas.");
    }

    String category = detectCategory(lower);

    // Deteksi Pemasukan / Pengeluaran
    String jenis = 'Pengeluaran';
    if (lower.contains('pemasukan') ||
        lower.contains('dapat') ||
        lower.contains('gaji') ||
        lower.contains('terima')) {
      jenis = 'Pemasukan';
    } else if (lower.contains('transfer') ||
        lower.contains('kirim') ||
        lower.contains('pindah')) {
      jenis = 'Transfer';
    }

    String note = text.isNotEmpty
        ? text[0].toUpperCase() + text.substring(1)
        : 'Transaksi Suara';

    return {
      'amount': amount,
      'category': category,
      'jenis': jenis,
      'note': note,
    };
  }
}
